// client/src/components/TracksContainer.jsx
import React from 'react';
import Track from './Track.jsx'

const TracksContainer = (props) => {
  const tracks = props.tracks;

  return (
    <div id="tracksContainer">
      {tracks.map((sound, i) => {
          return (
            <Track 
              className="track" key={`track${i}`} 
              sound={sound} index={i} words={props.words}
              changeWords={props.changeWords} />
          );
      })}
    </div>
  );
};

export default TracksContainer;

// client/src/components/TracksContainer.svelte
<script>
  import Track from './Track.svelte';

  export let words;
  export let tracks;
  export let changeWords;
</script>

<div id="tracksContainer">
  {#each tracks as track, index} 
    <Track mp3={track.mp3} bank={track.id} {index} {words} {changeWords}/>
  {/each}
</div>

<style>
  #tracksContainer {
    display: flex;
    flex-direction: column;
    width: 95%;
  }
</style>
