// sveltekit/svelteKit/src/lib/TracksContainer.svelte
<script lang='ts'>
  import Track from './Track.svelte';
  
  export let step: number;
  export let words: string[];
  export let tracks;
  export let changeWords;
</script>

<div id="tracksContainer">
  {#each tracks as track, index} 
    <Track {step} mp3={track.mp3} bank={track.id} {index} {words} {changeWords}/>
  {/each}
</div>

<style>
  #tracksContainer {
    display: flex;
    flex-direction: column;
    width: 95%;
  }
</style>

// client/src/old-react-components/TracksContainer.jsx
import React from 'react';
import Track from './Track.jsx'

const TracksContainer = (props) => {
  const tracks = props.tracks;

  return (
    <div id="tracksContainer">
      {tracks.map((sound, i) => {
          return (
            <Track 
              className="track" key={`track${i}`} mp3={sound.mp3}
              name={sound.id} index={i} words={props.words}
              changeWords={props.changeWords} />
          );
      })}
    </div>
  );
};

export default TracksContainer;
